export const PERMISSIONS = {
  ORGANIZATION_READ: "organization.read",
  ORGANIZATION_UPDATE: "organization.update",
  ORGANIZATION_BILLING_MANAGE: "organization.billing.manage",
  MEMBERS_READ: "members.read",
  MEMBERS_INVITE: "members.invite",
  MEMBERS_UPDATE: "members.update",
  MEMBERS_REMOVE: "members.remove",
  ROLES_READ: "roles.read",
  ROLES_MANAGE: "roles.manage",
  WHATSAPP_READ: "whatsapp.read",
  WHATSAPP_CONNECT: "whatsapp.connect",
  WHATSAPP_DISCONNECT: "whatsapp.disconnect",
  WHATSAPP_DELETE: "whatsapp.delete",
  CONTACTS_READ: "contacts.read",
  CONTACTS_CREATE: "contacts.create",
  CONTACTS_UPDATE: "contacts.update",
  CONTACTS_DELETE: "contacts.delete",
  CONVERSATIONS_READ: "conversations.read",
  CONVERSATIONS_REPLY: "conversations.reply",
  CONVERSATIONS_ASSIGN: "conversations.assign",
  CONVERSATIONS_CLOSE: "conversations.close",
  CONVERSATIONS_DELETE: "conversations.delete",
  CONVERSATIONS_EXPORT: "conversations.export",
  AI_READ: "ai.read",
  AI_CONFIGURE: "ai.configure",
  AI_PUBLISH: "ai.publish",
  AI_TOGGLE: "ai.toggle",
  KNOWLEDGE_READ: "knowledge.read",
  KNOWLEDGE_UPLOAD: "knowledge.upload",
  KNOWLEDGE_UPDATE: "knowledge.update",
  KNOWLEDGE_DELETE: "knowledge.delete",
  TRAINING_READ: "training.read",
  TRAINING_MANAGE: "training.manage",
  ANALYTICS_READ: "analytics.read",
  ANALYTICS_EXPORT: "analytics.export",
  INTEGRATIONS_READ: "integrations.read",
  INTEGRATIONS_MANAGE: "integrations.manage",
  AUDIT_READ: "audit.read",
  SETTINGS_MANAGE: "settings.manage",
  MARKETING_READ: "marketing.read",
  MARKETING_PRODUCTS_MANAGE: "marketing.products.manage",
  MARKETING_LEADS_MANAGE: "marketing.leads.manage",
  MARKETING_CAMPAIGNS_MANAGE: "marketing.campaigns.manage",
  MARKETING_CAMPAIGNS_START: "marketing.campaigns.start",
  MARKETING_DNC_MANAGE: "marketing.dnc.manage",
  MARKETING_SETTINGS_MANAGE: "marketing.settings.manage",
  MARKETING_ANALYTICS_READ: "marketing.analytics.read",
  VOICE_READ: "voice.read",
  VOICE_AGENT_MANAGE: "voice.agent.manage",
  VOICE_NUMBERS_MANAGE: "voice.numbers.manage",
  VOICE_SETTINGS_MANAGE: "voice.settings.manage",
  VOICE_CALLS_READ: "voice.calls.read",
  VOICE_RECORDINGS_ACCESS: "voice.recordings.access",
  VOICE_ANALYTICS_READ: "voice.analytics.read",
  VOICE_DIAGNOSTICS_RUN: "voice.diagnostics.run",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// Feature-entitlement keys for the AI Sales & Marketing module.
// Stored per-organization in the `entitlements` table; AI_SALES_MODULE is
// the master switch checked by the API guard, the rest gate sub-features.
export const MARKETING_CAPABILITIES = {
  AI_SALES_MODULE: "AI_SALES_MODULE",
  PRODUCT_CATALOG: "PRODUCT_CATALOG",
  LEAD_DISCOVERY: "LEAD_DISCOVERY",
  LEAD_IMPORT: "LEAD_IMPORT",
  MARKETING_CAMPAIGNS: "MARKETING_CAMPAIGNS",
  AI_PERSONALIZATION: "AI_PERSONALIZATION",
  AI_SALES_AGENT: "AI_SALES_AGENT",
  DO_NOT_CONTACT: "DO_NOT_CONTACT",
  SALES_ANALYTICS: "SALES_ANALYTICS",
  SALES_SETTINGS: "SALES_SETTINGS",
} as const;

export type MarketingCapability = (typeof MARKETING_CAPABILITIES)[keyof typeof MARKETING_CAPABILITIES];

// Feature-entitlement keys for the AI Voice Employee module.
// AI_VOICE_MODULE is the master switch checked by the API guard; the rest
// gate sub-features so an organization can hold a partial voice plan.
export const VOICE_CAPABILITIES = {
  AI_VOICE_MODULE: "AI_VOICE_MODULE",
  VOICE_AGENT_MANAGEMENT: "VOICE_AGENT_MANAGEMENT",
  VOICE_NUMBERS: "VOICE_NUMBERS",
  VOICE_TOOLS: "VOICE_TOOLS",
  VOICE_KNOWLEDGE: "VOICE_KNOWLEDGE",
  VOICE_ANALYTICS: "VOICE_ANALYTICS",
  VOICE_RECORDINGS: "VOICE_RECORDINGS",
  VOICE_VERIFICATION: "VOICE_VERIFICATION",
  VOICE_USAGE: "VOICE_USAGE",
  VOICE_SETTINGS: "VOICE_SETTINGS",
  VOICE_DIAGNOSTICS: "VOICE_DIAGNOSTICS",
} as const;

export type VoiceCapability = (typeof VOICE_CAPABILITIES)[keyof typeof VOICE_CAPABILITIES];

export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  PLATFORM_SUPER_ADMIN: Object.values(PERMISSIONS),
  ORGANIZATION_OWNER: Object.values(PERMISSIONS),
  ORGANIZATION_ADMIN: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_INVITE,
    PERMISSIONS.MEMBERS_UPDATE,
    PERMISSIONS.MEMBERS_REMOVE,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.WHATSAPP_READ,
    PERMISSIONS.WHATSAPP_CONNECT,
    PERMISSIONS.WHATSAPP_DISCONNECT,
    PERMISSIONS.WHATSAPP_DELETE,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.CONTACTS_DELETE,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_REPLY,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.CONVERSATIONS_CLOSE,
    PERMISSIONS.CONVERSATIONS_EXPORT,
    PERMISSIONS.AI_READ,
    PERMISSIONS.AI_CONFIGURE,
    PERMISSIONS.AI_PUBLISH,
    PERMISSIONS.AI_TOGGLE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.KNOWLEDGE_UPDATE,
    PERMISSIONS.KNOWLEDGE_DELETE,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.TRAINING_MANAGE,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.INTEGRATIONS_READ,
    PERMISSIONS.INTEGRATIONS_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  SUPPORT_MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.MEMBERS_READ,
    PERMISSIONS.MEMBERS_INVITE,
    PERMISSIONS.WHATSAPP_READ,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_REPLY,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.CONVERSATIONS_CLOSE,
    PERMISSIONS.AI_READ,
    PERMISSIONS.AI_TOGGLE,
    PERMISSIONS.KNOWLEDGE_READ,
    PERMISSIONS.KNOWLEDGE_UPLOAD,
    PERMISSIONS.TRAINING_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  SUPPORT_AGENT: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.WHATSAPP_READ,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_CREATE,
    PERMISSIONS.CONTACTS_UPDATE,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_REPLY,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.AI_READ,
    PERMISSIONS.KNOWLEDGE_READ,
  ],
  ANALYST: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
  ],
  READ_ONLY: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.ANALYTICS_READ,
  ],
};

export function hasPermission(rolePermissions: string[], required: PermissionCode): boolean {
  return rolePermissions.includes(required);
}

export function hasAnyPermission(rolePermissions: string[], required: PermissionCode[]): boolean {
  return required.some((p) => rolePermissions.includes(p));
}

export function hasAllPermissions(rolePermissions: string[], required: PermissionCode[]): boolean {
  return required.every((p) => rolePermissions.includes(p));
}
